//query.js
db.personne.drop()

conn = new Mongo();
db = conn.getDB("personne");
db.personne.insert([{
    _id:ObjectId("59418102bb63d6ab4db45cc3"),
    "prenom": "Garold",
    "nom": "Ladewig",
    "email": "gladewig0@umn.edu",
    "mot_de_passe": "5wIPDxwxZQ",
    "photo": "http://dummyimage.com/215x115.bmp/ff4444/ffffff",
    "date_naissance": "21-Sep-1999",
    "nom_lieu_travail": "Psycle Research",
    "code_postal_lieu_travail": "60200",
    "adresse_lieu_travail": "Rue roger coutollenc",
    "lien_social":[ 
      {_id:"59418102bb63d6ab4db45cc2","type":"ami"},
      {_id:"59418102bb63d6ab4db45cc4","type":"collègue"},
      {_id:"59418102bb63d6ab4db45cc5","type":"ami"}
    ],
    "dossier_thematique":[
      {"nom":"Favoris", "publique":1}
    ],
    "post":[{
      "id":"1", 
      "titre":"Ce que j'aime",
      "contenu":"J'ai trouvé cette image, vous en pensez quoi ??",
      "appartient_a":"Post_sans_interet",
      "date":"30-Mar-2019",
      "publique":1,
      "ami":1,
      "collegue":0,
      "famille":1,
    },
    {
      "id":"2", 
      "titre":"vidéo drôle",
      "url_Video":"https://youtu.be/cyW2ajAVyfA",
      "date":"20-Jun-2019",
      "publique":1,
      "ami":1,
      "collegue":0,
      "famille":1,
    },
    {
      "id":"3",
      "titre":"neige",
      "hauteur":194,
      "largeur":270, 
      "url_image":"https://cdn.xl.thumbs.canstockphoto.fr/aiguilles-dans-hiver-photos-sous-licence_csp6529053.jpg",
      "date":"20-Jun-2019",
      "publique":0,
      "ami":1,
      "collegue":0,
      "famille":1,
    }
    ]
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45cc2"),
    "prenom": "Mace",
    "nom": "Dando",
    "email": "mdando1@t-online.de",
    "mot_de_passe": "tZSYF9",
    "photo": "http://dummyimage.com/168x127.png/dddddd/000000",
    "date_naissance": "17-Dec-1984",
    "nom_lieu_travail": "Psycle Research",
    "code_postal_lieu_travail": "60200",
    "adresse_lieu_travail": "Rue roger coutollenc",
    "lien_social":[ {_id:"59418102bb63d6ab4db45cc3","type":"ami"}
    ],
    "post":[{
      "id":"1", 
      "titre":"Image de pluie",
      "hauteur":"1170",
      "largeur":"1860",
      "url_image": "https://fotomelia.com/wp-content/uploads/edd/2015/08/images-photos-gratuites-libre-de-droit34-1560x1170.jpg", 
      "appartient_a":"Post_sans_interet",
      "date":"30-Mar-2018",
      "publique":1,
      "ami":1,
      "collegue":0,
      "famille":1,
    }  
    ]
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45cc5"),
    "prenom": "Andee",
    "nom": "Cornborough",
    "email": "acornborough2@oakley.com",
    "mot_de_passe": "vKsTcqM8He0",
    "photo": "http://dummyimage.com/102x194.png/5fa2dd/ffffff",
    "date_naissance": "14-Jul-1973",
    "nom_lieu_travail": "Tantamare",
    "code_postal_lieu_travail": "80320",
    "adresse_lieu_travail": "Route Saint-Jaux",
    "post":[{
      "id":"1", 
      "titre":"Vlog en Antartique ! :-)",
      "url_video": "https://youtu.be/3caAitEusSw" , 
      "appartient_a":"Ensemble de mes podcasts",
      "date":"30-Mar-2019",
      "publique":1,
      "ami":1,
      "collegue":0,
      "famille":1,
    },
    {
      "id":"2", 
      "titre":"tuto installer linux",
      "url_video":"https://youtu.be/cyW2ajAVyfA",
      "date":"20-Jun-2019",
      "publique":1,
      "ami":1,
      "collegue":0,
      "famille":1,
    },
    {
      "id":"3",
      "titre":"ski à Veysonnaz!",
      "hauteur":194,
      "largeur":270, 
      "url_image":"https://cdn.xl.thumbs.canstockphoto.fr/aiguilles-dans-hiver-photos-sous-licence_csp6529053.jpg",
      "image": 1, 
      "date":"20-Jun-2019",
      "publique":0,
      "ami":1,
      "collegue":0,
      "famille":1,
    }
    ]
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45cc6"),    
    "prenom": "Rob",
    "nom": "Lennarde",
    "email": "rlennarde3@cbslocal.com",
    "mot_de_passe": "vo6pI4PwsD1",
    "photo": "http://dummyimage.com/100x192.bmp/5fa2dd/ffffff",
    "date_naissance": "07-Feb-1989",
    "nom_lieu_travail": "Hyper",
    "code_postal_lieu_travail": "89000",
    "adresse_lieu_travail": "33 Place du General Weygand",
    "post":[{
      "id":"1", 
      "titre":"Problème signal en C",
      "url_image": "https://fotomelia.com/wp-content/uploads/edd/2015/08/images-photos-gratuites-libre-de-droit34-1560x1170.jpg", 
      "hauteur":"1170",
      "largeur":"1860",
      "date":"25-Mar-2018",
      "publique":1,
      "ami":1,
      "collegue":0,
      "famille":1,
    }  
    ]
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45cc7"),    
    "prenom": "Tracee",
    "nom": "Millwater",
    "email": "tmillwater4@t.co",
    "mot_de_passe": "eSPqOoD",
    "photo": "http://dummyimage.com/191x191.png/dddddd/000000",
    "date_naissance": "07-Sep-1981",
    "nom_lieu_travail": "Hyper",
    "code_postal_lieu_travail": "89000",
    "adresse_lieu_travail": "33 Place du General Weygand"
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45cc8"),    
    "prenom": "Garrick",
    "nom": "Haith",
    "email": "ghaith5@ca.gov",
    "mot_de_passe": "jPW7mRE",
    "photo": "http://dummyimage.com/136x123.bmp/ff4444/ffffff",
    "date_naissance": "04-Aug-1988",
    "nom_lieu_travail": "Hulu Lab",
    "code_postal_lieu_travail": "75001",
    "adresse_lieu_travail": "32 Rue des moineaux"
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45cc9"),    
    "prenom": "Grantley",
    "nom": "Whitmore",
    "email": "gwhitmore6@adobe.com",
    "mot_de_passe": "5u5ZKxq7X6Tz",
    "photo": "http://dummyimage.com/177x233.png/cc0000/ffffff",
    "date_naissance": "07-Jun-1993",
    "nom_lieu_travail": "Hulu Lab",
    "code_postal_lieu_travail": "75001",
    "adresse_lieu_travail": "32 Rue des moineaux"
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45c10"),    
    "prenom": "Madelin",
    "nom": "Romaines",
    "email": "mromaines7@dagondesign.com",
    "mot_de_passe": "3wP0WjhXu",
    "photo": "http://dummyimage.com/116x151.bmp/cc0000/ffffff",
    "date_naissance": "17-Aug-1985",
    "nom_lieu_travail": "Hulu Lab",
    "code_postal_lieu_travail": "75001",
    "adresse_lieu_travail": "32 Rue des moineaux"
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45c11"),    
    "prenom": "Page",
    "nom": "Kretschmer",
    "email": "pkretschmer8@amazon.co.jp",
    "mot_de_passe": "ZUhQwR7y2vkh",
    "photo": "http://dummyimage.com/185x118.bmp/cc0000/ffffff",
    "date_naissance": "25-May-1992",
    "nom_lieu_travail": "Oracle",
    "code_postal_lieu_travail": "38600",
    "adresse_lieu_travail": "13 Route des fromagers"
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45c12"),    
    "prenom": "Dudley",
    "nom": "Carsey",
    "email": "dcarsey9@plala.or.jp",
    "mot_de_passe": "gz9wJgh9",
    "photo": "http://dummyimage.com/238x123.jpg/cc0000/ffffff",
    "date_naissance": "28-Feb-1982",
    "nom_lieu_travail": "Hulu Lab",
    "code_postal_lieu_travail": "75001",
    "adresse_lieu_travail": "32 Rue des moineaux"
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45c13"),    
    "prenom": "Ediva",
    "nom": "Pavlenko",
    "email": "epavlenkoa@dyndns.org",
    "mot_de_passe": "swKVnL498",
    "photo": "http://dummyimage.com/160x205.png/ff4444/ffffff",
    "date_naissance": "31-May-1989",
    "nom_lieu_travail": "Raptor Industries",
    "code_postal_lieu_travail": "60300",
    "adresse_lieu_travail": "56 Rue du Colonel Blanchard"
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45c14"),    
    "prenom": "Teresa",
    "nom": "Dearness",
    "email": "tdearnessb@ustream.tv",
    "mot_de_passe": "SmE8JajsND",
    "photo": "http://dummyimage.com/129x198.bmp/5fa2dd/ffffff",
    "date_naissance": "21-Mar-1975",
    "nom_lieu_travail": "Psycle Research",
    "code_postal_lieu_travail": "60200",
    "adresse_lieu_travail": "Rue roger coutollenc"
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45c16"),    
    "prenom": "Penelopa",
    "nom": "Denisovich",
    "email": "pdenisovichc@usda.gov",
    "mot_de_passe": "o6JF3c1",
    "photo": "http://dummyimage.com/145x175.bmp/dddddd/000000",
    "date_naissance": "29-Feb-1976",
    "nom_lieu_travail": "Raptor Industries",
    "code_postal_lieu_travail": "60300",
    "adresse_lieu_travail": "56 Rue du Colonel Blanchard"
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45c17"),    
    "prenom": "Meghan",
    "nom": "Scuffham",
    "email": "mscuffhamd@admin.ch",
    "mot_de_passe": "jevgAYNh",
    "photo": "http://dummyimage.com/236x213.png/cc0000/ffffff",
    "date_naissance": "25-Feb-1996",
    "nom_lieu_travail": "Psycle Research",
    "code_postal_lieu_travail": "60200",
    "adresse_lieu_travail": "Rue roger coutollenc"
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45c18"),    
    "prenom": "Wynne",
    "nom": "Merryweather",
    "email": "wmerryweathere@de.vu",
    "mot_de_passe": "AIPUhdnXQat",
    "photo": "http://dummyimage.com/160x220.jpg/5fa2dd/ffffff",
    "date_naissance": "09-Apr-1975",
    "nom_lieu_travail": "Raptor Industries",
    "code_postal_lieu_travail": "60300",
    "adresse_lieu_travail": "56 Rue du Colonel Blanchard"
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45c19"),    
    "prenom": "Denice",
    "nom": "Slot",
    "email": "dslotf@examiner.com",
    "mot_de_passe": "JHn9Smxb",
    "photo": "http://dummyimage.com/127x125.bmp/dddddd/000000",
    "date_naissance": "26-Oct-1999",
    "nom_lieu_travail": "Raptor Industries",
    "code_postal_lieu_travail": "60300",
    "adresse_lieu_travail": "56 Rue du Colonel Blanchard"
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45c20"),    
    "prenom": "Avigdor",
    "nom": "Durnan",
    "email": "adurnang@histats.com",
    "mot_de_passe": "nJTi2iVv",
    "photo": "http://dummyimage.com/188x107.bmp/cc0000/ffffff",
    "date_naissance": "13-Jan-1977",
    "nom_lieu_travail": "Psycle Research",
    "code_postal_lieu_travail": "60200",
    "adresse_lieu_travail": "Rue roger coutollenc"
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45c21"),    
    "prenom": "Erek",
    "nom": "Bucktrout",
    "email": "ebucktrouth@squarespace.com",
    "mot_de_passe": "mNo1xPQ",
    "photo": "http://dummyimage.com/196x201.png/ff4444/ffffff",
    "date_naissance": "05-May-1996",
    "nom_lieu_travail": "Raptor Industries",
    "code_postal_lieu_travail": "60300",
    "adresse_lieu_travail": "56 Rue du Colonel Blanchard"
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45c22"),    
    "prenom": "Dyanna",
    "nom": "Maynard",
    "email": "dmaynardi@drupal.org",
    "mot_de_passe": "h5HUILw1",
    "photo": "http://dummyimage.com/139x161.jpg/cc0000/ffffff",
    "date_naissance": "08-May-1971",
    "nom_lieu_travail": "Raptor Industries",
    "code_postal_lieu_travail": "60300",
    "adresse_lieu_travail": "56 Rue du Colonel Blanchard"
  },
  {
    _id:ObjectId("59418102bb63d6ab4db45c23"),    
    "prenom": "Suzette",
    "nom": "Wettern",
    "email": "swetternj@about.me",
    "mot_de_passe": "728o71Qzlfp",
    "photo": "http://dummyimage.com/164x249.png/5fa2dd/ffffff",
    "date_naissance": "27-Apr-1979",
    "nom_lieu_travail": "Oracle",
    "code_postal_lieu_travail": "38600",
    "adresse_lieu_travail": "13 Route des fromagers"
  }
]);